"""Card add view_count

Revision ID: 2600a2201df0
Revises: e0dfc922e366
Create Date: 2019-02-15 10:57:24.412224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2600a2201df0'
down_revision = 'e0dfc922e366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'view_count')
    # ### end Alembic commands ###
