"""Add company name

Revision ID: 594c22ba95f3
Revises: a15c0e554fbe
Create Date: 2019-01-23 16:07:25.974804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594c22ba95f3'
down_revision = 'a15c0e554fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('company_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'company_name')
    # ### end Alembic commands ###
