"""Add card image_path

Revision ID: 5ca3ad97a1af
Revises: 594c22ba95f3
Create Date: 2019-01-23 16:14:33.920853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca3ad97a1af'
down_revision = '594c22ba95f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('image_path', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'image_path')
    # ### end Alembic commands ###
