"""Card card_anime_path and card_cosplay_path add default

Revision ID: ab995d99f031
Revises: f30e5dc53196
Create Date: 2019-02-18 15:27:24.757809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab995d99f031'
down_revision = 'f30e5dc53196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('anime_path', sa.String(length=64), nullable=True))
    op.add_column('cards', sa.Column('cosplay_path', sa.String(length=64), nullable=True))
    op.drop_column('cards', 'card_cosplay_path')
    op.drop_column('cards', 'card_anime_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_anime_path', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True))
    op.add_column('cards', sa.Column('card_cosplay_path', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True))
    op.drop_column('cards', 'cosplay_path')
    op.drop_column('cards', 'anime_path')
    # ### end Alembic commands ###
