"""Modles GroupActivityLog add companion

Revision ID: b305272b63d9
Revises: e9a6c59fb2f2
Create Date: 2019-03-25 09:12:40.763406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b305272b63d9'
down_revision = 'e9a6c59fb2f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_activity_logs', sa.Column('companion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_activity_logs', 'companion')
    # ### end Alembic commands ###
