"""Fix user lin_user_id uniqe

Revision ID: b709f3cbfa10
Revises: 5ca3ad97a1af
Create Date: 2019-01-28 13:28:36.069578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b709f3cbfa10'
down_revision = '5ca3ad97a1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('line_user_id', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('line_user_id', 'users', ['line_user_id'], unique=True)
    # ### end Alembic commands ###
