"""Change Activity to GroupActivity

Revision ID: c28f001ddcee
Revises: 031d1b412265
Create Date: 2019-02-25 10:24:55.652993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c28f001ddcee'
down_revision = '031d1b412265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_activity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_activity_id'], ['group_activitys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('activity_logs')
    op.add_column('activitys', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activitys', 'users', ['user_id'], ['id'])
    op.drop_column('activitys', 'source_type')
    op.drop_column('activitys', 'source_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitys', sa.Column('source_id', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True))
    op.add_column('activitys', sa.Column('source_type', mysql.VARCHAR(collation='utf8_unicode_ci', length=64), nullable=True))
    op.drop_constraint(None, 'activitys', type_='foreignkey')
    op.drop_column('activitys', 'user_id')
    op.create_table('activity_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activitys.id'], name='activity_logs_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='activity_logs_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('group_activity_logs')
    # ### end Alembic commands ###
