"""Add member

Revision ID: e131410d0998
Revises: 22135cbd4b7e
Create Date: 2019-01-17 15:49:52.131582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e131410d0998'
down_revision = '22135cbd4b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('source_id', table_name='members')
    op.drop_index('source_type', table_name='members')
    op.drop_column('members', 'arn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('arn', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('source_type', 'members', ['source_type'], unique=True)
    op.create_index('source_id', 'members', ['source_id'], unique=True)
    # ### end Alembic commands ###
