"""GroupActivity Add activity_type

Revision ID: e9a6c59fb2f2
Revises: d4f851755a24
Create Date: 2019-03-05 14:15:13.175706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9a6c59fb2f2'
down_revision = 'd4f851755a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pic_logs')
    op.add_column('group_activitys', sa.Column('activity_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_activitys', 'activity_type')
    op.create_table('pic_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('result', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf16le',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
